name: Android Build & Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  android-build:
    runs-on: ubuntu-latest
    
    env:
      KOTLIN_NATIVE_IGNORE_ILLEGAL_MULTIPLATFORM_MODULES: 1
      KOTLIN_NATIVE_IGNORE_ILLEGAL_MULTIPLATFORM_MODULES_WARNING: 1
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Show Gradle version
      run: ./gradlew --version
      
    - name: Build Android only
      run: ./gradlew androidApp:assembleDebug --stacktrace
      
    - name: Run Android tests
      run: ./gradlew androidApp:test --stacktrace
      
    - name: Build shared module (Android target only)
      run: ./gradlew shared:compileDebugKotlinAndroid --stacktrace
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-debug-apk
        path: androidApp/build/outputs/apk/debug/androidApp-debug.apk 